USE ONLINESTOREDB;
GO
IF
    NOT EXISTS (
        SELECT 1 FROM SYS.SCHEMAS
        WHERE NAME = 'test_OrderOps'
    )
    EXEC TSQLT.NEWTESTCLASS 'test_OrderOps';
GO
CREATE OR ALTER PROCEDURE TEST_ORDEROPS.[test CloseOrder closes and totals]
AS
BEGIN
    EXEC TSQLT.FAKETABLE 'dbo.Orders';
    EXEC TSQLT.FAKETABLE 'dbo.OrderDetails';

    INSERT DBO.ORDERS (ORDERID, CUSTOMERID, ORDERDATE, TOTALAMOUNT, CREATEDAT, UPDATEDAT, STATUS)
    VALUES (1, 1, SYSUTCDATETIME(), 0, SYSUTCDATETIME(), SYSUTCDATETIME(), 'Open');

    INSERT DBO.ORDERDETAILS (ORDERID, PRODUCTID, QUANTITY, UNITPRICE, CREATEDAT, UPDATEDAT)
    VALUES (1, 1, 2, 10.00, SYSUTCDATETIME(), SYSUTCDATETIME()); -- Subtotal=20

    EXEC DBO.CLOSEORDER @OrderID = 1;

    EXEC TSQLT.ASSERTEQUALS 'Closed', (
        SELECT STATUS FROM DBO.ORDERS
        WHERE ORDERID = 1
    );
    EXEC TSQLT.ASSERTEQUALS 20.00, (
        SELECT TOTALAMOUNT FROM DBO.ORDERS
        WHERE ORDERID = 1
    );
END;
GO
