USE ONLINESTOREDB;
GO
IF SCHEMA_ID('OrderOpsTests') IS NULL
    EXEC TSQLT.NEWTESTCLASS @ClassName = N'OrderOpsTests';
GO
CREATE OR ALTER PROCEDURE ORDEROPSTESTS.[test_CloseOrder_sets_status_Closed]
AS
BEGIN
    -- Arrange
    EXEC TSQLT.FAKETABLE @TableName = N'dbo.Orders';
    EXEC TSQLT.FAKETABLE @TableName = N'dbo.OrderDetails';
    EXEC TSQLT.FAKETABLE @TableName = N'dbo.Products';

    INSERT DBO.PRODUCTS (PRODUCTID, NAME, PRICE, STOCKQUANTITY, CREATEDAT, UPDATEDAT)
    VALUES (1, N'Widget', 10.00, 100, SYSUTCDATETIME(), SYSUTCDATETIME());

    INSERT DBO.ORDERS (ORDERID, CUSTOMERID, ORDERDATE, STATUS, TOTALAMOUNT, CREATEDAT, UPDATEDAT)
    VALUES (100, 1, SYSUTCDATETIME(), N'Open', 20.00, SYSUTCDATETIME(), SYSUTCDATETIME());

    INSERT DBO.ORDERDETAILS (ORDERDETAILID, ORDERID, PRODUCTID, QUANTITY, UNITPRICE, SUBTOTAL, CREATEDAT, UPDATEDAT)
    VALUES (200, 100, 1, 2, 10.00, 20.00, SYSUTCDATETIME(), SYSUTCDATETIME());

    -- Act
    EXEC DBO.CLOSEORDER @OrderID = 100;

    -- Assert
    DECLARE @actual nvarchar(
        20) = (
        SELECT STATUS FROM DBO.ORDERS
        WHERE ORDERID = 100
    );
    EXEC TSQLT.ASSERTEQUALSSTRING @Expected = N'Closed', @Actual = @actual, @Message = N'Status should be Closed';
END;
GO
