SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF DB_ID('OnlineStoreDB') IS NULL
    CREATE DATABASE ONLINESTOREDB;
GO
USE ONLINESTOREDB;
GO

IF OBJECT_ID('dbo.OrderDetails', 'U') IS NOT NULL DROP TABLE DBO.ORDERDETAILS;
IF OBJECT_ID('dbo.Orders', 'U') IS NOT NULL DROP TABLE DBO.ORDERS;
IF OBJECT_ID('dbo.Products', 'U') IS NOT NULL DROP TABLE DBO.PRODUCTS;
IF OBJECT_ID('dbo.Customers', 'U') IS NOT NULL DROP TABLE DBO.CUSTOMERS;
GO

CREATE TABLE DBO.CUSTOMERS (
    CUSTOMERID INT IDENTITY (1, 1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL UNIQUE,
    ADDRESS NVARCHAR(255) NULL,
    CREATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_CUSTOMERS_CREATEDAT DEFAULT SYSUTCDATETIME(),
    UPDATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_CUSTOMERS_UPDATEDAT DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE DBO.PRODUCTS (
    PRODUCTID INT IDENTITY (1, 1) PRIMARY KEY,
    NAME NVARCHAR(150) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL CHECK (PRICE >= 0),
    STOCKQUANTITY INT NOT NULL CHECK (STOCKQUANTITY >= 0),
    CREATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_PRODUCTS_CREATEDAT DEFAULT SYSUTCDATETIME(),
    UPDATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_PRODUCTS_UPDATEDAT DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE DBO.ORDERS (
    ORDERID INT IDENTITY (1, 1) PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    ORDERDATE DATETIME2(0) NOT NULL CONSTRAINT DF_ORDERS_ORDERDATE DEFAULT SYSUTCDATETIME(),
    TOTALAMOUNT DECIMAL(12, 2) NOT NULL CONSTRAINT DF_ORDERS_TOTAL DEFAULT 0,
    CREATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_ORDERS_CREATEDAT DEFAULT SYSUTCDATETIME(),
    UPDATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_ORDERS_UPDATEDAT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMERID) REFERENCES DBO.CUSTOMERS (CUSTOMERID)
);
GO

CREATE TABLE DBO.ORDERDETAILS (
    ORDERDETAILID INT IDENTITY (1, 1) PRIMARY KEY,
    ORDERID INT NOT NULL,
    PRODUCTID INT NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
    UNITPRICE DECIMAL(10, 2) NOT NULL CHECK (UNITPRICE >= 0),
    SUBTOTAL AS (QUANTITY * UNITPRICE) PERSISTED,
    CREATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_ORDERDETAILS_CREATEDAT DEFAULT SYSUTCDATETIME(),
    UPDATEDAT DATETIME2(0) NOT NULL CONSTRAINT DF_ORDERDETAILS_UPDATEDAT DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY (ORDERID) REFERENCES DBO.ORDERS (ORDERID),
    CONSTRAINT FK_ORDERDETAILS_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES DBO.PRODUCTS (PRODUCTID)
);
GO

CREATE INDEX IX_ORDERS_CUSTOMERID_ORDERDATE ON DBO.ORDERS (CUSTOMERID, ORDERDATE DESC);
CREATE INDEX IX_ORDERDETAILS_ORDERID ON DBO.ORDERDETAILS (ORDERID);
CREATE INDEX IX_ORDERDETAILS_PRODUCTID ON DBO.ORDERDETAILS (PRODUCTID);
CREATE INDEX IX_PRODUCTS_NAME ON DBO.PRODUCTS (NAME);
GO
