USE ONLINESTOREDB;
GO

CREATE OR ALTER VIEW DBO.VWORDERSUMMARY AS
SELECT
    O.ORDERID,
    O.CUSTOMERID,
    O.ORDERDATE,
    O.TOTALAMOUNT,
    COUNT(OD.ORDERDETAILID) AS LINECOUNT
FROM DBO.ORDERS AS O
LEFT JOIN DBO.ORDERDETAILS AS OD ON O.ORDERID = OD.ORDERID
GROUP BY O.ORDERID, O.CUSTOMERID, O.ORDERDATE, O.TOTALAMOUNT;
GO

CREATE OR ALTER VIEW DBO.VWBESTSELLERS30D AS
SELECT TOP 20
    OD.PRODUCTID,
    P.NAME,
    SUM(OD.QUANTITY) AS UNITSSOLD,
    SUM(OD.SUBTOTAL) AS REVENUE
FROM DBO.ORDERDETAILS AS OD
INNER JOIN DBO.ORDERS AS O ON OD.ORDERID = O.ORDERID
INNER JOIN DBO.PRODUCTS AS P ON OD.PRODUCTID = P.PRODUCTID
WHERE O.ORDERDATE >= DATEADD(DAY, -30, SYSUTCDATETIME())
GROUP BY OD.PRODUCTID, P.NAME
ORDER BY UNITSSOLD DESC, REVENUE DESC;
GO
