USE ONLINESTOREDB;
GO

/* Generic UpdatedAt triggers */
CREATE OR ALTER TRIGGER TRG_CUSTOMERS_UPDATEDAT
ON DBO.CUSTOMERS AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE C SET UPDATEDAT = SYSUTCDATETIME()
    FROM DBO.CUSTOMERS AS C
    INNER JOIN INSERTED AS I ON C.CUSTOMERID = I.CUSTOMERID;
END;
GO

CREATE OR ALTER TRIGGER TRG_PRODUCTS_UPDATEDAT
ON DBO.PRODUCTS AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE P SET UPDATEDAT = SYSUTCDATETIME()
    FROM DBO.PRODUCTS AS P
    INNER JOIN INSERTED AS I ON P.PRODUCTID = I.PRODUCTID;
END;
GO

CREATE OR ALTER TRIGGER TRG_ORDERS_UPDATEDAT
ON DBO.ORDERS AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE O SET UPDATEDAT = SYSUTCDATETIME()
    FROM DBO.ORDERS AS O
    INNER JOIN INSERTED AS I ON O.ORDERID = I.ORDERID;
END;
GO

CREATE OR ALTER TRIGGER TRG_ORDERDETAILS_UPDATEDAT
ON DBO.ORDERDETAILS AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE D SET UPDATEDAT = SYSUTCDATETIME()
    FROM DBO.ORDERDETAILS AS D
    INNER JOIN INSERTED AS I ON D.ORDERDETAILID = I.ORDERDETAILID;
END;
GO
