USE ONLINESTOREDB;
GO
/* Add Status column if missing */
IF COL_LENGTH('dbo.Orders', 'Status') IS NULL
    BEGIN
        ALTER TABLE DBO.ORDERS ADD STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_ORDERS_STATUS DEFAULT ('Open');
    END;
GO

/* Index for common filters */
IF
    NOT EXISTS (
        SELECT 1 FROM SYS.INDEXES
        WHERE NAME = 'IX_Orders_Status_OrderDate' AND OBJECT_ID = OBJECT_ID('dbo.Orders')
    )
    CREATE INDEX IX_ORDERS_STATUS_ORDERDATE ON DBO.ORDERS (STATUS, ORDERDATE DESC);
GO
