USE ONLINESTOREDB;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER VIEW DBO.VWORDERSUMMARYWITHSTATUS AS
SELECT
    O.ORDERID,
    O.CUSTOMERID,
    O.ORDERDATE,
    O.STATUS,
    O.TOTALAMOUNT,
    COUNT(OD.ORDERDETAILID) AS LINECOUNT
FROM DBO.ORDERS AS O
LEFT JOIN DBO.ORDERDETAILS AS OD ON O.ORDERID = OD.ORDERID
GROUP BY O.ORDERID, O.CUSTOMERID, O.ORDERDATE, O.STATUS, O.TOTALAMOUNT;
GO
