USE ONLINESTOREDB;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* Supporting index for quick scans by quantity */
IF
    NOT EXISTS (
        SELECT 1 FROM SYS.INDEXES
        WHERE NAME = 'IX_Products_StockQuantity' AND OBJECT_ID = OBJECT_ID('dbo.Products')
    )
    CREATE INDEX IX_PRODUCTS_STOCKQUANTITY ON DBO.PRODUCTS (STOCKQUANTITY ASC);
GO

/* NOTE: No ORDER BY in the view. Sort when querying/reporting. */
CREATE OR ALTER VIEW DBO.VWLOWSTOCK AS
SELECT
    PRODUCTID,
    NAME,
    STOCKQUANTITY
FROM DBO.PRODUCTS
WHERE STOCKQUANTITY < 10;
GO
