USE ONLINESTOREDB;
GO

/* Last 30 days revenue by day */
SELECT
    CAST(ORDERDATE AS DATE) AS [Day],
    SUM(TOTALAMOUNT) AS REVENUE
FROM DBO.ORDERS
WHERE ORDERDATE >= DATEADD(DAY, -30, SYSUTCDATETIME())
GROUP BY CAST(ORDERDATE AS DATE)
ORDER BY [Day] DESC;

/* Top customers */
SELECT TOP 10
    C.CUSTOMERID,
    C.NAME,
    SUM(O.TOTALAMOUNT) AS SPEND
FROM DBO.CUSTOMERS AS C
INNER JOIN DBO.ORDERS AS O ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERID, C.NAME
ORDER BY SPEND DESC;

/* Low stock alerts */
SELECT
    PRODUCTID,
    NAME,
    STOCKQUANTITY
FROM DBO.PRODUCTS
WHERE STOCKQUANTITY < 10
ORDER BY STOCKQUANTITY ASC;

/* Best sellers (view) */
SELECT * FROM DBO.VWBESTSELLERS30D
ORDER BY UNITSSOLD DESC;
