name: DB CI (build + smoke + tSQLt)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: db-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Start SQL Server via Docker Compose
        run: |
          docker compose -f docker/docker-compose.yml up -d
          # Wait up to ~8 minutes for health
          for i in {1..160}; do
            if docker ps --filter "name=store-mssql" --filter "health=healthy" --format "{{.Status}}" | grep -qi healthy; then
              echo "SQL Server is healthy."; break
            fi
            echo "Waiting for SQL Server..."; sleep 3
          done
          docker ps
          # Small buffer after health turns healthy
          sleep 10

      - name: Apply SQL (schema → procs → triggers → views → seed → extras)
        run: |
          set -e
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -i /var/opt/sql/01_schema.sql
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -i /var/opt/sql/04_procs.sql || true
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -i /var/opt/sql/05_triggers.sql || true
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -i /var/opt/sql/03_views.sql || true
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -i /var/opt/sql/02_seed.sql || true
          for f in /var/opt/sql/06_migrations.sql /var/opt/sql/07_order_ops.sql /var/opt/sql/08_views_status.sql /var/opt/sql/09_view_low_stock.sql /var/opt/sql/10_constraints.sql /var/opt/sql/11_categories.sql /var/opt/sql/12_close_order.sql; do
            if docker exec store-mssql sh -lc "[ -f \"$f\" ]"; then
              echo "Applying $f"
              /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -i "$f" || true
            fi
          done

      - name: Prepare DB for tSQLt (enable CLR, TRUSTWORTHY ON, owner sa)
        run: |
          # Server-level
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -Q "EXEC sp_configure 'show advanced options',1; RECONFIGURE;"
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -Q "EXEC sp_configure 'clr enabled',1; RECONFIGURE;"
          # Database-level trust & owner (needed for CLR strict security)
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -Q "ALTER DATABASE OnlineStoreDB SET TRUSTWORTHY ON;"
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -Q "USE OnlineStoreDB; EXEC sys.sp_changedbowner 'sa';"

      - name: Install tSQLt (vendored)
        run: |
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d OnlineStoreDB -i "/var/opt/sql/tests/_tSQLt/tSQLt.class.sql"

      - name: Run test bootstrap & suite (tSQLt.RunAll)
        run: |
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d OnlineStoreDB -i "/var/opt/sql/tests/_bootstrap.sql"
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d OnlineStoreDB -i "/var/opt/sql/tests/10_OrderOps_Tests.sql"
          /usr/bin/docker exec -i store-mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d OnlineStoreDB -Q "EXEC tSQLt.RunAll;"

      - name: Diagnostics on failure
        if: failure() || always()
        run: |
          docker ps
          docker logs store-mssql | tail -n 200 || true
